config/routes.rb
Oa::Application.routes.draw do

  resources :unpaid_debts do
    member do
        get 'verify'
    end
  end
  resources :reimbursements do
    member do
        get 'verify'
    end
  end

  resources :in_comes
  resources :transfers
  resources :expenditures

  resources :acceptances
  resources :bank_accounts

  resources :tasks
  resources :deliveries

  resources :out_stores
  resources :in_stores

  resources :attendances

  resources :messages do
     collection do
        get "get_unread"
     end
  end

  resources :attaches
  resources :announcements

  resources :notes

  resources :supl_contracts
  resources :sales_contracts

  resources :clients
  resources :suppliers

  resources :groups

  devise_scope :user do
    get "/users/sign_out", :to => "devise/sessions#destroy"
  end
  devise_for :users, :controllers => {:registrations=>"registrations",:sessions=>'sessions'} ,:path_prefix => 'devise'
  resources :users

  root :to => 'home#main'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content
end

app/controllers/announcements_controller.rb
#!/bin/env ruby
# encoding: utf-8
class AnnouncementsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :except=>:index
  # GET /announcements
  # GET /announcements.json
  def index
    @announcement = Announcement.last

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.json
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = current_user.announcements.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: '公告 成功创建.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.json
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to @announcement, notice: '公告 成功更新.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url }
      format.json { head :no_content }
    end
  end
          
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label '内容' %>
    <%= f.text_area :content ,:size => "20x5" %>
  </div>
  <div class="actions">
    <%= f.submit '发布公告' ,:class=>'btn btn-success' %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>编辑公告</h1>

<%= render 'form' %>

<%= link_to '显示', @announcement %> |
<%= link_to '返回', announcements_path %>

app/views/announcements/index.html.erb
<div class="span3 thumbnail">
  <div class='caption'>
    <h4>公告:</h4>
    <h3>
      <%= @announcement.content unless @announcement.nil? %>
    </h3>
    <br />
    <% if can? :manage, Announcement %>
      <a href='/announcements/new'><i class='icon-plus'></i>发布公告</a>
    <%end%>
  </div>
</div>

app/views/announcements/new.html.erb
<h1>新公告</h1>

<%= render 'form' %>

<%= link_to '返回', announcements_path %>

app/views/announcements/show.html.erb
<table class="table table-bordered show_table">
  <tr>
    <td>内容</td>
    <td><%= @announcement.content %></td>
  </tr>
  <tr>
    <td>用户</td>
    <td><%= @announcement.user.username %></td>
  </tr>
</table>
<%= link_to '编辑', edit_announcement_path(@announcement) %> |
<%= link_to '返回', announcements_path %>