config/routes.rb
Oa::Application.routes.draw do

  resources :unpaid_debts do
    member do
        get 'verify'
    end
  end
  resources :reimbursements do
    member do
        get 'verify'
    end
  end

  resources :in_comes
  resources :transfers
  resources :expenditures

  resources :acceptances
  resources :bank_accounts

  resources :tasks
  resources :deliveries

  resources :out_stores
  resources :in_stores

  resources :attendances

  resources :messages do
     collection do
        get "get_unread"
     end
  end

  resources :attaches
  resources :announcements

  resources :notes

  resources :supl_contracts
  resources :sales_contracts

  resources :clients
  resources :suppliers

  resources :groups

  devise_scope :user do
    get "/users/sign_out", :to => "devise/sessions#destroy"
  end
  devise_for :users, :controllers => {:registrations=>"registrations",:sessions=>'sessions'} ,:path_prefix => 'devise'
  resources :users

  root :to => 'home#main'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/unpaid_debt.rb
class UnpaidDebt < ActiveRecord::Base
  attr_accessible :caption, :money, :status ,:group_id ,:number
  belongs_to :group
end

app/controllers/unpaid_debts_controller.rb
#!/bin/env ruby
# encoding: utf-8
class UnpaidDebtsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /unpaid_debts
  # GET /unpaid_debts.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: UnpaidDebtsDatatable.new(view_context) }
    end
  end

  # GET /unpaid_debts/1
  # GET /unpaid_debts/1.json
  def show
    @unpaid_debt = UnpaidDebt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unpaid_debt }
    end
  end

  # GET /unpaid_debts/new
  # GET /unpaid_debts/new.json
  def new
    @unpaid_debt = UnpaidDebt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unpaid_debt }
    end
  end

  # GET /unpaid_debts/1/edit
  def edit
    @unpaid_debt = UnpaidDebt.find(params[:id])
  end

  # POST /unpaid_debts
  # POST /unpaid_debts.json
  def create
    unless params[:unpaid_debt][:status].nil? or isManager?
      redirect_to unpaid_debts_url, :alert => '您没有权限进行此操作'
      return
    end
    @unpaid_debt = UnpaidDebt.new(params[:unpaid_debt])

    respond_to do |format|
      if @unpaid_debt.save
        format.html { redirect_to unpaid_debts_url, notice: '挂帐单 成功创建.' }
        format.json { render json: @unpaid_debt, status: :created, location: @unpaid_debt }
      else
        format.html { render action: "new" }
        format.json { render json: @unpaid_debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unpaid_debts/1
  # PUT /unpaid_debts/1.json
  def update
    unless params[:unpaid_debt][:status].nil? or isManager?
      redirect_to unpaid_debts_url, :alert => '您没有权限进行此操作'
      return
    end
    @unpaid_debt = UnpaidDebt.find(params[:id])

    respond_to do |format|
      if @unpaid_debt.update_attributes(params[:unpaid_debt])
        format.html { redirect_to @unpaid_debt, notice: '挂帐单 成功更新.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unpaid_debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unpaid_debts/1
  # DELETE /unpaid_debts/1.json
  def destroy
    @unpaid_debt = UnpaidDebt.find(params[:id])
    @unpaid_debt.destroy

    respond_to do |format|
      format.html { redirect_to unpaid_debts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/unpaid_debts_helper.rb
#!/bin/env ruby
# encoding: utf-8
module UnpaidDebtsHelper
    def debts_status(i)
        debts_status_list.insert(0,'等待中')[i]
    end
    def debts_status_list
        ['同意','不同意','已付']
    end
    def debts_status_select
        debts_status_list.zip(1..debts_status_list.length)
    end
end

app/views/unpaid_debts/_form.html.erb
<%= form_for(@unpaid_debt) do |f| %>
  <% if @unpaid_debt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unpaid_debt.errors.count, "error") %> prohibited this unpaid_debt from being saved:</h2>

      <ul>
      <% @unpaid_debt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label '部门' %>
    <%= f.collection_select(:group_id, Group.all, :id, :name,{:prompt=>''} ,{:class=>"chzn-select","data-placeholder"=>"请选择"}) %>
  </div>
  <div class="field">
    <%= f.label '金额' %>
    <%= f.text_field :money %>
  </div>
  <div class="field">
    <%= f.label '说明' %>
    <%= f.text_area :caption ,:size => "20x5" %>
  </div>
  <% unless @unpaid_debt.new_record? or !isManager?%>
      <div class="field">
          <%= f.label "状态" %>
          <%= f.select(:status, debts_status_select ) %>
      </div>
  <% end %>
  <% if @unpaid_debt.status ==1 %>
      <div class="field">
          <%= f.label "凭证编号" %>
          <%= f.text_field :number %>
      </div>
  <% end %>
  <div class="actions">
    <%= f.submit '提交挂帐单'  ,:class=>'btn btn-success' %>
  </div>
<% end %>

app/views/unpaid_debts/edit.html.erb
<h1>编辑挂帐单</h1>

<%= render 'form' %>

<%= link_to '显示', @unpaid_debt %> |
<%= link_to '返回', unpaid_debts_path %>

app/views/unpaid_debts/index.html.erb
<%= javascript_include_tag "datatable" %>
<%= stylesheet_link_tag "table"%>
<%= javascript_include_tag "unpaid_debts" %>
<table id ="unpaid_debts" class="table table-striped table-bordered" data-source="<%= unpaid_debts_url(format: "json") %>" >
  <thead>
    <tr>
      <th>状态</th>
      <th>部门</th>
      <th>金额</th>
      <th>时间</th>
      <th>编辑</th>
    </tr>
  </thead>
  <tbody></tbody>
</table>

app/views/unpaid_debts/new.html.erb
<h1>新挂账单</h1>

<%= render 'form' %>

<%= link_to '返回', unpaid_debts_path %>

app/views/unpaid_debts/show.html.erb
<table class="table show_table table-bordered">
  <tr>
    <td>金额</td>
    <td><%= @unpaid_debt.money %></td>
  </tr>
  <tr>
    <td>说明</td>
    <td><%= @unpaid_debt.caption %></td>
  </tr>
  <tr>
    <td>状态</td>
    <td><%= debts_status @unpaid_debt.status %></td>
  </tr>
</table>
<%= link_to '编辑', edit_unpaid_debt_path(@unpaid_debt) %> |
<%= link_to '返回', unpaid_debts_path %>