config/routes.rb
Oa::Application.routes.draw do

  resources :unpaid_debts do
    member do
        get 'verify'
    end
  end
  resources :reimbursements do
    member do
        get 'verify'
    end
  end

  resources :in_comes
  resources :transfers
  resources :expenditures

  resources :acceptances
  resources :bank_accounts

  resources :tasks
  resources :deliveries

  resources :out_stores
  resources :in_stores

  resources :attendances

  resources :messages do
     collection do
        get "get_unread"
     end
  end

  resources :attaches
  resources :announcements

  resources :notes

  resources :supl_contracts
  resources :sales_contracts

  resources :clients
  resources :suppliers

  resources :groups

  devise_scope :user do
    get "/users/sign_out", :to => "devise/sessions#destroy"
  end
  devise_for :users, :controllers => {:registrations=>"registrations",:sessions=>'sessions'} ,:path_prefix => 'devise'
  resources :users

  root :to => 'home#main'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/ability.rb
#!/bin/env ruby
# encoding: utf-8
class Ability
  include CanCan::Ability

  def initialize(user)
    
      user ||= User.new # guest user (not logged in)
      ga= user.groups.map{|g| g.org_group_access}
      ua= user.groups.map{|u| u.org_user_access}
      gids= user.groups.map(&:id)

      if ga.map{|g| g.include?"C"}.include?true
        can :create, Group
      end
      if ga.map{|g| g.include?"R"}.include?true
        can :read, Group
      end
      if ga.map{|g| g.include?"U"}.include?true
        can :update, Group
      end
      if ga.map{|g| g.include?"D"}.include?true
        can :destroy, Group
      end

      if ua.map{|g| g.include?"C"}.include?true
        can :create, User
      end
      if ua.map{|g| g.include?"R"}.include?true
        can :read, User
      end
      if ua.map{|g| g.include?"U"}.include?true
        can :update, User
      end
      if ua.map{|g| g.include?"D"}.include?true
        can :destroy, User
      end

      #总经理
      if gids.include?2
        can :manage, [Announcement]
      end

      #供销部
      if gids.include?3
        can :manage, [Client,Supplier,SuplContract,SalesContract]
      end

      #财务部
      if gids.include?4 or gids.include?2
        can :manage, [Attendance,BankAccount,Expenditure,InCome,Acceptance,Transfer,UnpaidDebt,Reimbursement]
      end

      #库房
      if gids.include?5
        can :manage, [InStore,OutStore]
      end

      #车间
      if gids.include?6
        can :manage, [Task,Delivery]
      end

  end
end

app/models/acceptance.rb
#!/bin/env ruby
# encoding: utf-8
class Acceptance < ActiveRecord::Base
  attr_accessible :bank, :expire, :unit, :status ,:expenditure_id ,:number
  belongs_to :in_come
  belongs_to :expenditure

  def name
    "#{bank} #{in_come.money}"
  end

  def self.All
      self.where(:status=>nil)
  end
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content
end

app/models/attach.rb
class Attach < ActiveRecord::Base
  # belongs_to :supl_contract
  attr_accessible :picture
  
  has_attached_file :picture
  validates_attachment_presence :picture
  validates_attachment_size :picture, :less_than => 10.megabytes
  validates_attachment_content_type :picture, :content_type => [ 'image/jpeg', 'image/png', 'image/pjpeg' ]
  
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  attr_accessible :caption,:attach_ids,:for_month
end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  attr_accessible :accountname, :bankname, :over
  has_many :in_comes

  def name
    "#{bankname} #{accountname}"
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :sales_contracts
  attr_accessible :name ,:goods ,:address ,:contact ,:contact_person

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  attr_accessible :caption ,:client,:goods,:attach_ids
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
  attr_accessible :mode, :money, :payto, :bank_account_id
  belongs_to :bank_account
  has_one :acceptance
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  attr_accessible :name ,:org_group_access ,:org_user_access
  has_many :unpaid_debts
end

app/models/in_come.rb
#!/bin/env ruby
# encoding: utf-8
class InCome < ActiveRecord::Base
  attr_accessible :mode, :money, :from ,:fromtime ,:bank_account_id
  belongs_to :bank_account
  has_one :acceptance

end

app/models/in_store.rb
class InStore < ActiveRecord::Base
  attr_accessible :caption ,:name,:attach_ids
  has_many :acceptances
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :title
end

app/models/out_store.rb
class OutStore < ActiveRecord::Base
  attr_accessible :caption ,:name,:person,:attach_ids
end

app/models/reimbursement.rb
class Reimbursement < ActiveRecord::Base
  attr_accessible :caption, :money, :status ,:user_id ,:category
  belongs_to :user
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :supl_contracts
  attr_accessible :name ,:goods ,:address ,:contact ,:contact_person

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :caption ,:attach_ids
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  attr_accessible :caption ,:attach_ids ,:money
  has_many :acceptances
end

app/models/unpaid_debt.rb
class UnpaidDebt < ActiveRecord::Base
  attr_accessible :caption, :money, :status ,:group_id ,:number
  belongs_to :group
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :user
  attr_accessible :picture
  
  has_attached_file :picture
  validates_attachment_presence :picture
  validates_attachment_size :picture, :less_than => 5.megabytes
  validates_attachment_content_type :picture, :content_type => [ 'image/jpeg', 'image/png', 'image/pjpeg' ]
  
end

app/models/user.rb
#!/bin/env ruby
# encoding: utf-8
class User < ActiveRecord::Base
  acts_as_messageable

  has_many :announcements
  has_many :notes
  has_many :reimbursements
  has_and_belongs_to_many :groups
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :name, :password,:password_confirmation, :remember_me
  attr_accessible :group_ids

  validates_uniqueness_of :username,:on=>:create,:message=>"用户名已被使用!"
end

app/controllers/groups_controller.rb
#!/bin/env ruby
# encoding: utf-8

class GroupsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to groups_url, :alert => '您没有权限进行此操作'
  end

  # GET /groups
  # GET /groups.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: GroupsDatatable.new(view_context) }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url , notice: '机构 被成功创建.'}
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to groups_url, notice: '机构 被成功修改.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url , notice: '机构 被成功删除 .'}
      format.json { head :no_content }
    end
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "名称" %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "新建" ,:class=>'btn btn-success' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<style type="text/css">
  table
  {
    font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse:collapse;
  }

  table td, table th 
  {
    font-size:1em;
    border:1px solid #98bf21;
    padding:3px 7px 2px 7px;
  }

  table th 
  {
    font-size:1.1em;
    text-align:left;
    padding-top:5px;
    padding-bottom:4px;
    background-color:#A7C942;
    color:#ffffff;
  }

  table td 
  {
    color:#000000;
    background-color:#EAF2D3;
  }
</style>
<h2>给 <span style="font-style:italic;"><%= @group.name %> </span> 授权</h2>

<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <table>
      <tr>
        <th colspan="4"> 机构管理 </th>
      </tr>
      <tr>
        <% ['C','R','U','D'].each do |e| %>
          <td>
            <label>
              <%= e %>
              <%= check_box_tag "group[org_group_access][]",
                e, (checked = true if @group.org_group_access.include?e) %>
              </label>
            </td>
          <% end %>
        </tr>
      </table>
    </div>
    <br />
    <div class="field">
      <table>
        <tr>
          <th colspan="4"> 人员管理 </th>
        </tr>
        <tr>
          <% ['C','R','U','D'].each do |e| %>
            <td>
              <label> <%= e %>
                <%= check_box_tag "group[org_user_access][]",
                  e, (checked = true if @group.org_user_access.include?e) %>
                </label>
              </td>
            <% end %>
          </tr>
        </table>
      </div>
      <br />

      <div class="actions">
        <%= f.submit '授权' ,:class=>'btn btn-success' %>
      </div>
    <% end %>

    <%= link_to '返回', groups_path %>

app/views/groups/index.html.erb
<%= javascript_include_tag "datatable" %>
<%= stylesheet_link_tag "table"%>
<%= javascript_include_tag "groups" %>
<table id ="groups" class="table table-striped table-bordered" data-source="<%= groups_url(format: "json") %>" >
  <thead>
    <tr>
      <th>ID</th>
      <th>机构名称</th>
      <th>创建时间</th>
      <th>编辑</th>
    </tr>
  </thead>
  <tbody></tbody>
</table>

app/views/groups/new.html.erb
<h1>新建 机构</h1>

<%= render 'form' %>

<%= link_to '返回', groups_path %>

app/views/groups/show.html.erb
<% @groups.each do |g| %>
  <tr class="repeat" align="center">
    <td height="18" bgcolor="#FFFFFF">
      <div align="center" class="STYLE1">
        <input name="checkbox" type="checkbox" class="STYLE2" value="checkbox">
      </div>
    </td>
    <td height="18" bgcolor="#FFFFFF" class="STYLE2">
      <span align="center" display:block;line-height:100%;="" class="STYLE2 STYLE1"><%= g.id %></span>
    </td>
    <td height="18" bgcolor="#FFFFFF">
      <span align="center" display:block;line-height:100%;="" class="STYLE2 STYLE1"><%= g.name%></span>
    </td>
    <td height="18" bgcolor="#FFFFFF">
      <span align="center" display:block;line-height:100%;="" class="STYLE2 STYLE1"><%=  %></span>
    </td>
    <td height="18" bgcolor="#FFFFFF" align="center">
      <span display:block;line-height:100%;="" class="STYLE2 STYLE1"><%= g.created_at %></span>
    </td>
    <td height="18" bgcolor="#FFFFFF">
      <div align="center" class="STYLE1">
        <img src="/assets/tab/images/037.gif" width="9" height="9">[
        
        
        <%= link_to '编辑', edit_group_path(g) ,{:target=>'I1'} %>
        
        <!-- <a href="/groups/<%= g.id %>/edit" target='I1'>编辑</a> -->
        ]
      </div>
    </td>
    <td height="18" bgcolor="#FFFFFF">
      <div align="center" class="STYLE1">
        <img src="/assets/tab/images/010.gif" width="9" height="9">[
        <%= link_to '删除', g, method: :delete, data: { confirm: '确定删除 ?' } %>
        ]
      </div>
    </td>
  </tr>
<% end %>