config/routes.rb
Oa::Application.routes.draw do

  resources :unpaid_debts do
    member do
        get 'verify'
    end
  end
  resources :reimbursements do
    member do
        get 'verify'
    end
  end

  resources :in_comes
  resources :transfers
  resources :expenditures

  resources :acceptances
  resources :bank_accounts

  resources :tasks
  resources :deliveries

  resources :out_stores
  resources :in_stores

  resources :attendances

  resources :messages do
     collection do
        get "get_unread"
     end
  end

  resources :attaches
  resources :announcements

  resources :notes

  resources :supl_contracts
  resources :sales_contracts

  resources :clients
  resources :suppliers

  resources :groups

  devise_scope :user do
    get "/users/sign_out", :to => "devise/sessions#destroy"
  end
  devise_for :users, :controllers => {:registrations=>"registrations",:sessions=>'sessions'} ,:path_prefix => 'devise'
  resources :users

  root :to => 'home#main'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  attr_accessible :caption ,:attach_ids ,:money
  has_many :acceptances
end

app/controllers/transfers_controller.rb
#!/bin/env ruby
# encoding: utf-8
class TransfersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /transfers
  # GET /transfers.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: TransfersDatatable.new(view_context) }
    end
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
    @transfer = Transfer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transfer }
    end
  end

  # GET /transfers/new
  # GET /transfers/new.json
  def new
    @transfer = Transfer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transfer }
    end
  end

  # GET /transfers/1/edit
  def edit
    @transfer = Transfer.find(params[:id])
  end

  # POST /transfers
  # POST /transfers.json
  def create
    begin
      params[:transfer][:attach_ids]=params[:transfer][:attach_ids].join(",")
    rescue => err
      p err
    end
    rm_unneed_attach
    
    @transfer=Transfer.new(params[:transfer])
    respond_to do |format|
      if @transfer.save
        format.html { redirect_to transfers_url, notice: '转帐单 成功创建.' }
        format.json { render json: @transfer, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /transfers/1
  # PUT /transfers/1.json
  def update
    begin
      params[:transfer][:attach_ids]=params[:transfer][:attach_ids].join(",")
    rescue => err
      p err
    end
    rm_unneed_attach

    @transfer = Transfer.find(params[:id])
    respond_to do |format|
      if @transfer.update_attributes(params[:transfer])
        format.html { redirect_to @transfer, notice: '转帐单 成功更新.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer = Transfer.find(params[:id])
    @transfer.destroy

    respond_to do |format|
      format.html { redirect_to transfers_url }
      format.json { head :no_content }
    end
  end

  private

  def rm_unneed_attach()
    begin
      Attach.find(params[:unneed_attach][:attach_ids]).each do |a|
        a.destroy
      end
    rescue => err
      p err
    end
  end
end

app/views/transfers/_form.html.erb
<style type="text/css">
  #file_upload_progress {
    background: url(<%= asset_path("uploads/progressbar.gif") %>);
  }

  #file_upload_progress  {
    display: none;
    width: 150px;
    height: 15px;
  }
  #doneFile {
    background-color: #E9E1D4;
    margin-top: 8px;
    margin-bottom: 4px;
    padding: 5px;
  }
  #attach_picture {display:none;}
  #a {
    color: #4C5C7C;
  }
  body ,#doneFile{
    color: black;
    font-size: 12px;
    line-height: 166.6%;
  }
  table td {
    border: 2px;
    padding: 1px 7px 1px 7px;
  }
</style>


<%= form_for(@transfer, :html=>{:id => 'mainform' }) do |c| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>
      <ul>
        <% @transfer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div id="hiddenfile">
      <% unless c.object.new_record? or c.object.attach_ids.nil? %>
        <% c.object.attach_ids.split(',').each do |e| %>
          <input name="transfer[attach_ids][]"" type="hidden" value= "<%= e %>" />
        <% end %>
      <% end %>
  </div>


  <div class="field">
    <%= c.label "金额" %>
    <%= c.text_field :money %>
  </div>
  <div class="field">
    <%= c.label "说明" %>
    <%= c.text_area :caption ,:size => "20x5" %>
  </div>

<% end %>

<%= form_tag "/attaches",  :id => "fileupload", :multipart => true  do |c| %>
  <div title="可以添加任意附件">
    附件:
    <a id="addAttach" href="/#">添加附件</a>
    <%= file_field_tag 'attach[picture]', :multiple => true %>
  </div>

  <div id="file_upload_progress"></div>
<% end %>

<div>
  <table id="doneFile">
    <tbody>
      <% unless @transfer.new_record? or @transfer.attach_ids.nil? %>
         <% Attach.where(:id => @transfer.attach_ids.split(',')).each do |a|  %>
          <tr class="template-upload fade in">
            <td class="name"><span>  <%= a.picture_file_name %> </span></td> 
            <td class="size"><span size=<%= a.picture_file_size %> >
                wait...</span></td>
            <td class="progess"><span>100 %</span></td>
            <td class="download">
              <%= link_to '下载', a.picture.url%>
            </td>
            <td class="destroy">  
              <%= link_to '删除', a%>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<input id="submit" name="commit" type="submit" value="提交转帐单" class='btn btn-success'/>

<%= javascript_include_tag "fileupload" %>

<script>
  $(document).ready(function(){
  $("#doneFile").click(function(){
    var e=e||window.event;
    var obj=e.target||e.srcElement;
    var item=$(obj);
    if (item.is('td.destroy>a'))
    {
    var id=item.attr("href").match(/\d+/);
      item.parents('tr').remove();
      if (id==null) return false;
      var select="#hiddenfile input[value=" +id[0]+ "]";
      $(select).attr("name","unneed_attach[attach_ids][]");
      return false;
    }
  });


  $("#submit").click(function(){$("#mainform").submit()});
  $("#addAttach").click(function(){$("#attach_picture").trigger("click");return false;});
    function d(b){
      if ( isNaN(b))
      return;
      dws=['b','Kb','Mb'];
      for(i=0;i<3;i++){
        dw=dws[i];
        if (b<1024) break;
        b=b/1024;
      }
      return b.toFixed(2)+dw;
    };
    var size=$("#doneFile td.size span");
    size.text(d(parseInt(size.attr("size"))));
    $('#fileupload').fileupload({
      done: function (e, data) {
      if (data.result.error==true){
      $("#doneFile>tbody").append('<tr class="template-upload fade in"><td class="name"><span>'+data.result.msg+'</span></td> <td class="size"><span></span></td> <td class="progess"><span></span></td> <td></td> <td class="destroy"><a href="/#">删除</a></td></tr>');
        return;
      }
        $("#hiddenfile").append('<input type="hidden" name="transfer[attach_ids][]" value='+data.result.id+'\>')
        $("#doneFile>tbody").append('<tr class="template-upload fade in"><td class="name"><span>'+data.result.name+'</span></td> <td class="size"><span>'+d(data.result.size)+'</span></td> <td class="progess"><span>100 %</span></td> <td class="download"><a href="'+ data.result.a_path +'">下载</a></td> <td class="destroy"><a href="/attaches/'+data.result.id+'">删除</a></td></tr>');
      },
      start: function (e) {
        $("#file_upload_progress").fadeIn();
      },
      stop:function (e) {
        $("#file_upload_progress").fadeOut();
      },

    });
  });
</script>

app/views/transfers/edit.html.erb
<h1>编辑转帐单</h1>

<%= render 'form' %>

<%= link_to '显示', @transfer %> |
<%= link_to '返回', transfers_path %>

app/views/transfers/index.html.erb
<%= javascript_include_tag "datatable" %>
<%= stylesheet_link_tag "table"%>
<%= javascript_include_tag "transfers" %>
<table id ="transfers" class="table table-striped table-bordered" data-source="<%= transfers_url(format: "json") %>" >
  <thead>
    <tr>
      <th>金额</th>
      <th>时间</th>
      <th>编辑</th>
    </tr>
  </thead>
  <tbody></tbody>
</table>

app/views/transfers/new.html.erb
<h1>新转帐单</h1>

<%= render 'form' %>

<%= link_to '返回', in_stores_path %>

app/views/transfers/show.html.erb
<style type="text/css">

  #file_upload_progress  {
    display: none;
    width: 150px;
    height: 15px;
  }
  #doneFile {
    background-color: #E9E1D4;
    margin-top: 8px;
    margin-bottom: 4px;
    padding: 5px;
  }
  #attach_picture {display:none;}
  #a {
    color: #4C5C7C;
  }
  #doneFile{
    color: black;
    font-size: 12px;
    line-height: 166.6%;
  }
  #doneFile td {
    border: 2px;
    padding: 1px 7px 1px 7px;
  }
</style>

<table class="table show_table table-bordered">
  <tr>
    <td>金额</td>
    <td><%= @transfer.money %></td>
  </tr>
  <tr>
    <td>说明</td>
    <td><%= @transfer.caption %></td>
  </tr>
</table>
<div>
  <table id="doneFile">
    <b>附件:</b>
    <tbody>
      <% unless @transfer.new_record? or @transfer.attach_ids.nil? %>
        <% Attach.where(:id => @transfer.attach_ids.split(',')).each do |a|  %>
          <tr class="template-upload fade in">
            <td class="name"><span>  <%= a.picture_file_name %> </span></td> 
            <td class="size"><span size=<%= a.picture_file_size %> >
                wait...</span></td>
            <td class="progess"><span>100 %</span></td>
            <td class="download">
              <%= link_to '下载', a.picture.url%>
            </td>
            <td class="destroy">  
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  $(document).ready(function(){
    function d(b){
      if ( isNaN(b))
      return;
      dws=['b','Kb','Mb'];
      for(i=0;i<3;i++){
        dw=dws[i];
        if (b<1024) break;
        b=b/1024;
      }
      return b.toFixed(2)+dw;
    };
    var size=$("#doneFile td.size span");
    size.text(d(parseInt(size.attr("size"))));
  });
</script>